// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApp2
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
 

    /// <summary>
    /// Extension methods for ConsoleApp2Client.
    /// </summary>
    public static partial class ConsoleApp2ClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<int?> ApiBirthdayWishExclusionsGet(this IConsoleApp2Client operations)
            {
                return Task.Factory.StartNew(s => ((IConsoleApp2Client)s).ApiBirthdayWishExclusionsGetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> ApiBirthdayWishExclusionsGetAsync(this IConsoleApp2Client operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiBirthdayWishExclusionsGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<Employee> ApiEmployeesGet(this IConsoleApp2Client operations)
            {
                return Task.Factory.StartNew(s => ((IConsoleApp2Client)s).ApiEmployeesGetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Employee>> ApiEmployeesGetAsync(this IConsoleApp2Client operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiEmployeesGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
